246 no cloudtype primary key
apel/apel pull request #250
Opened 2021-06-23 09:51 UTC by pjcon

2021-06-23 09:52 UTC, pjcon commented
I've not included versions in the schema update script.

2021-09-09 16:26 UTC, tofu-rocketry requested changes

2021-09-09 16:26 UTC, tofu-rocketry commented on scripts/update-x.x.x-x.x.x.sql
> +CREATE TABLE CloudSummaries (
We can't drop and recreate an existing table as part of an update schema as that'll drop the data it contains! This should be one or more `ALTER TABLE` statements to change the primary key.

2021-09-09 16:52 UTC, tofu-rocketry commented
Note that I've rebased this before you make any additions to this PR.

2021-09-20 12:33 UTC, pjcon reviewed
No longer dropping the table, but instead drop and readd the primary key without CloudType.

2021-09-23 14:30 UTC, tofu-rocketry approved these changes
Looks good. Just could do with a note on the manual testing.

2021-09-27 09:08 UTC, gregcorbett submitted a review, later dismissed
Do we need to remove CloudType from the `SummariseVMs` procedure? If we don't, won't we generate summaries that only differ by CloudType and then only one will get be kept.

2021-09-27 09:50 UTC, tofu-rocketry commented
> Do we need to remove CloudType from the `SummariseVMs` procedure? If we don't, won't we generate summaries that only differ by CloudType and then only one will get be kept.

Good point!

2024-09-17 09:58 UTC, tofu-rocketry commented
> Do we need to remove CloudType from the `SummariseVMs` procedure? If we don't, won't we generate summaries that only differ by CloudType and then only one will get be kept.

Ah, having a look at Connor's solution, we do want to take it out of the grouping, but we still want to select the CloudType from the later record, so that the latest CloudType is stored in the summaries. So I think we just need to revert the Null bit.

2024-09-17 10:24 UTC, gregcorbett commented
> Ah, having a look at Connor's solution, we do want to take it out of the grouping, but we still want to select the CloudType from the later record, so that the latest CloudType is stored in the summaries. So I think we just need to revert the Null bit.

So the idea being: if a site publishes a record with `{Month:8, Year: 2024, CloudType: Foo 1.0.0}` and then later republished with `{Month:8, Year: 2024, CloudType: Foo 1.1.1}` (and all other things being equal) we'd end up with a fresh summary showing `CloudType: Foo 1.1.1` and no stale summary for `CloudType: Foo 1.0.0`.

Is that correct?

If that's the case, I think this looks okay.

2024-09-17 10:30 UTC, tofu-rocketry commented
> So the idea being: if a site publishes a record with `{Month:8, Year: 2024, CloudType: Foo}` and then later republished with `{Month:8, Year: 2024, CloudType: Bar}` (and all other things being equal) we'd end up with a fresh summary showing `CloudType: Bar` and no stale summary for `CloudType: Foo`.
> 
> Is that correct?

Yeah, that's the idea. `SummariseVMs` should take care of preserving the later data for us, but we do want to keep the `CloudType` in the Summaries.

2024-09-17 10:31 UTC, gregcorbett approved these changes

2024-09-17 10:34 UTC, merged