Fix HTCondor format for trailing empty fields
apel/apel pull request #342
Opened 2023-12-20 15:03 UTC by maxfischer2781

This PR adjusts the `htcondor` parser to match its own example and HTCondor-CE. It is still compatible with the old format.

- HTCondor parser now ignores a trailing, *empty* field after all required ones. This means the final `|` can act both as a delimiter and terminator.
- The example is adjusted for consistency: The query now has a newline to make it feasible for multiple jobs, and the output has the trailing `|` of the query.

Closes #341.

2024-07-12 12:34 UTC, maxfischer2781 commented
Ugh, the Codacy lint now complains about the line length but that was already too long before. Breaking up the line to fit in the length seems counterproductive, since reproducing the actual format is kind of the point here.

What's the policy here? Should I break up the line regardless? If I'm reading the Codacy report right, this is just prettified Pylint report - is it okay to [disable the inspection for those lines or the entire block](https://pylint.readthedocs.io/en/latest/user_guide/messages/message_control.html#block-disables)?

2024-07-25 12:48 UTC, tofu-rocketry commented
Don't worry about the line length. I need to sort the code style checks to have a more generous limit, but that requires a general overhaul of the CI tools.

2025-02-24 13:44 UTC, maxfischer2781 commented
@tofu-rocketry Thanks for updating the style checks, this is ready for review.

2025-07-25 09:34 UTC, tofu-rocketry approved these changes

2025-07-25 09:37 UTC, tofu-rocketry requested changes
Oops, realised I should update the unit tests. Can sort that myself.

2025-07-29 15:03 UTC, tofu-rocketry approved these changes

2025-07-30 06:58 UTC, gregcorbett approved these changes
LGTM

2025-07-30 12:19 UTC, tofu-rocketry commented
Thanks, @gregcorbett

2025-07-30 12:20 UTC, merged