Initial draft for apel fpm build script
apel/apel pull request #351
Opened 2024-03-04 09:29 UTC by Sae126V

Script need fine-tuning and optimised.
Final check for script is needed.

2024-04-18 11:34 UTC, Sae126V commented
Rebased onto dev.

2024-04-18 15:57 UTC, Sae126V commented
Hi @tofu-rocketry and @gregcorbett . I have added `rpmlint` to the script.

2024-04-23 08:35 UTC, tofu-rocketry requested changes

2024-04-23 08:35 UTC, tofu-rocketry commented on scripts/apel-build.sh
> +rpmlint $RPMDIR
As per my comment on the SSM script, just collapse this to one line.

2024-05-01 13:29 UTC, tofu-rocketry approved these changes

2024-05-01 13:52 UTC, merged