Updated pre python 2.7 code
apel/apel pull request #371
Opened 2024-07-02 12:21 UTC by Will-Cross1

Mentions of using python versions before 2.7 have been updated to utilise features that are available in python 2.7+

Mentions of only python 2 have been ignored as 2.7 is included under it

Resolves #360

2024-07-02 14:12 UTC, tofu-rocketry requested changes

2024-07-02 14:30 UTC, Will-Cross1 commented on constraints.txt
>  # coveralls dependencies that need older versions for Python 2.6
Resolved in #fcbd42a

2024-07-02 14:30 UTC, Will-Cross1 commented on bin/parser.py
> +    for index, line in enumerate(fp, start=1):
Resolved in #fcbd42a

2024-07-03 08:58 UTC, tofu-rocketry approved these changes
Looks good.

2024-07-03 09:00 UTC, tofu-rocketry commented
Good commit messages too.

2024-07-03 09:03 UTC, merged